version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es01
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # จำกัดการใช้ RAM (แนะนำสำหรับเครื่อง dev)
    ports:
      - "9200:9200"
    volumes:
      - esdata01:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kib01
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  redis:
    image: "redis:alpine"
    container_name: redis01
    ports:
      - "6379:6379"

volumes:
  esdata01:
    driver: local
